name: Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ASPIRE_ALLOW_UNSECURED_TRANSPORT: true
    steps:
    - uses: actions/checkout@v4
    - name: Install Docker
      uses: docker/setup-docker-action@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Cache NuGet packages
      uses: actions/cache@v4
      id: cache-nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      if: steps.cache-nuget.outputs.cache-hit != 'true'
      run: dotnet restore
    - name: Install & trust dev-certs
      run: dotnet dev-certs https --trust
    - name: Build & Install
      run: |
        if [ ${{ steps.cache-nuget.outputs.cache-hit == 'true' }} ]; then
          dotnet build
        else
          dotnet build --no-restore
    - name: Cache Playwright binaries
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: |
          AspireTest.TestProject/bin/Debug/net9.0/.playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/*.csproj') }}
    - name: Ensure browsers are installed
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: pwsh AspireTest.TestProject/bin/Debug/net9.0/playwright.ps1 install --with-deps
    - name: Run tests
      run: dotnet test
